version: "3"
services:
  app-csr:
    build:
      dockerfile: infra/DockerfileCSR
    deploy:
      replicas: 1

  app-ssr:
    build:
      dockerfile: infra/DockerfileSSR
    deploy:
      replicas: 1

  gateway:
    image: "nginx:1.25.1-alpine3.17"
    ports:
      - "80:80"
    volumes:
      - "./infra/nginx-gateway.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app-csr
      - app-ssr